"""Tests for the shared, dialect-aware store DDL source."""

from __future__ import annotations

from dataclasses import replace

from ontary.store import _sql, schema
from ontary.store import postgres as postgres_store

_EXPECTED_POSTGRES_DDL = (
    "\n"
    "CREATE TABLE IF NOT EXISTS schema_meta (\n"
    "    key TEXT PRIMARY KEY,\n"
    "    value TEXT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS objects (\n"
    "    row_id BIGSERIAL PRIMARY KEY,\n"
    "    object_type TEXT NOT NULL,\n"
    "    id TEXT NOT NULL,\n"
    "    payload TEXT NOT NULL,\n"
    "    valid_from TEXT NOT NULL,\n"
    "    valid_to TEXT NULL,\n"
    "    source_system TEXT NOT NULL,\n"
    "    source_id TEXT NULL,\n"
    "    extracted_at TEXT NULL,\n"
    "    page_token TEXT NOT NULL,\n"
    "    type_version INTEGER NOT NULL DEFAULT 1,\n"
    "    tenant TEXT NOT NULL DEFAULT 'default'\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS links (\n"
    "    link_type TEXT NOT NULL,\n"
    "    from_id TEXT NOT NULL,\n"
    "    to_id TEXT NOT NULL,\n"
    "    valid_from TEXT NOT NULL,\n"
    "    valid_to TEXT NULL,\n"
    "    tenant TEXT NOT NULL DEFAULT 'default'\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS audit_log (\n"
    "    seq BIGSERIAL PRIMARY KEY,\n"
    "    ts TEXT NOT NULL,\n"
    "    actor TEXT NOT NULL,\n"
    "    role TEXT NOT NULL,\n"
    "    action TEXT NOT NULL,\n"
    "    target_type TEXT NOT NULL,\n"
    "    target_id TEXT NULL,\n"
    "    params TEXT NOT NULL,\n"
    "    outcome TEXT NOT NULL,\n"
    "    writes TEXT NOT NULL DEFAULT '[]',\n"
    "    effects TEXT NOT NULL DEFAULT '[]',\n"
    "    capability_accesses TEXT NOT NULL DEFAULT '[]',\n"
    "    invocation_id TEXT NULL,\n"
    "    kind TEXT NOT NULL DEFAULT 'action',\n"
    "    tenant TEXT NOT NULL DEFAULT 'default',\n"
    "    principal TEXT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS effect_outbox (\n"
    "    effect_id TEXT PRIMARY KEY,\n"
    "    invocation_id TEXT NOT NULL,\n"
    "    seq INTEGER NOT NULL,\n"
    "    api_name TEXT NOT NULL,\n"
    "    payload TEXT NOT NULL,\n"
    "    action TEXT NOT NULL,\n"
    "    actor_id TEXT NOT NULL,\n"
    "    role TEXT NOT NULL,\n"
    "    emitted_at TEXT NOT NULL,\n"
    "    state TEXT NOT NULL,\n"
    "    attempts INTEGER NOT NULL DEFAULT 0,\n"
    "    next_attempt_at TEXT NOT NULL,\n"
    "    lease_until TEXT NULL,\n"
    "    last_error TEXT NULL,\n"
    "    updated_at TEXT NOT NULL,\n"
    "    tenant TEXT NOT NULL DEFAULT 'default'\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS ontology_fingerprint (\n"
    "    id INTEGER PRIMARY KEY,\n"
    "    digest TEXT NOT NULL,\n"
    "    types TEXT NOT NULL,\n"
    "    first_seen TEXT NOT NULL,\n"
    "    adopted INTEGER NOT NULL DEFAULT 0,\n"
    "    versions TEXT NOT NULL DEFAULT '{}'\n"
    ");\n"
    "\n"
    "CREATE INDEX IF NOT EXISTS idx_objects_type_id\n"
    "    ON objects (tenant, object_type, id);\n"
    "CREATE INDEX IF NOT EXISTS idx_objects_type_rowid\n"
    "    ON objects (tenant, object_type, row_id);\n"
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_objects_page_token ON objects (page_token);\n"
    "CREATE INDEX IF NOT EXISTS idx_links_from ON links (tenant, link_type, from_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_links_to ON links (tenant, link_type, to_id);\n"
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_effect_outbox_invocation_seq\n"
    "    ON effect_outbox (invocation_id, seq);\n"
    "CREATE INDEX IF NOT EXISTS idx_effect_outbox_due\n"
    "    ON effect_outbox (tenant, state, next_attempt_at);\n"
)


def test_both_dialects_render_from_the_shared_table_specs() -> None:
    table_names = {table.name for table in _sql.TABLE_SPECS}
    assert table_names == {
        "schema_meta",
        "objects",
        "links",
        "audit_log",
        "effect_outbox",
        "ontology_fingerprint",
    }


def test_column_added_to_a_copied_spec_renders_in_both_dialects() -> None:
    objects = next(table for table in _sql.TABLE_SPECS if table.name == "objects")
    extended_objects = replace(
        objects,
        columns=objects.columns + (_sql.ColumnSpec("added_column", "TEXT", "NULL"),),
    )
    specs = tuple(
        extended_objects if table.name == "objects" else table for table in _sql.TABLE_SPECS
    )

    for dialect in ("sqlite", "postgres"):
        ddl = _sql.render_schema(dialect, table_specs=specs)
        assert "    added_column TEXT NULL\n" in ddl


def test_generated_postgres_ddl_is_pinned() -> None:
    assert postgres_store._SCHEMA_SQL == _EXPECTED_POSTGRES_DDL


_EXPECTED_SQLITE_DDL = (
    "\n"
    "-- `page_token` (pagination-hardening T2 amendment, spec §5): a\n"
    "-- fresh uuid4 hex written on EVERY row insert (including the\n"
    "-- new version `update`'s close-old-insert-new writes) -- the\n"
    "-- opaque cursor `read_page` hands out, resolved back to\n"
    "-- `row_id` via `idx_objects_page_token` below. This IS a schema\n"
    "-- change from the T1 shape; T4's `SCHEMA_VERSION` stamp must\n"
    "-- cover it (see that task).\n"
    "CREATE TABLE IF NOT EXISTS objects (\n"
    "    row_id INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    object_type TEXT NOT NULL,\n"
    "    id TEXT NOT NULL,\n"
    "    payload TEXT NOT NULL,\n"
    "    valid_from TEXT NOT NULL,\n"
    "    valid_to TEXT NULL,\n"
    "    source_system TEXT NOT NULL,\n"
    "    source_id TEXT NULL,\n"
    "    extracted_at TEXT NULL,\n"
    "    page_token TEXT NOT NULL,\n"
    "    -- Which version of the declared type this row's payload was written\n"
    "    -- under (M9b). Read by `ontary.upcast.upcast_payload` on every read;\n"
    "    -- written from the declaration on every insert/update.\n"
    "    type_version INTEGER NOT NULL DEFAULT 1,\n"
    "    -- Which tenant owns this row (M8b). NOT NULL with a default so the\n"
    "    -- single-tenant case needs no ceremony and a migrated row is never\n"
    "    -- ownerless: a NULL tenant would read as \"belongs to everybody\",\n"
    "    -- which is precisely wrong for an isolation column.\n"
    "    tenant TEXT NOT NULL DEFAULT 'default'\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS links (\n"
    "    link_type TEXT NOT NULL,\n"
    "    from_id TEXT NOT NULL,\n"
    "    to_id TEXT NOT NULL,\n"
    "    valid_from TEXT NOT NULL,\n"
    "    valid_to TEXT NULL,\n"
    "    tenant TEXT NOT NULL DEFAULT 'default'\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS audit_log (\n"
    "    seq INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    ts TEXT NOT NULL,\n"
    "    actor TEXT NOT NULL,\n"
    "    role TEXT NOT NULL,\n"
    "    action TEXT NOT NULL,\n"
    "    target_type TEXT NOT NULL,\n"
    "    target_id TEXT NULL,\n"
    "    params TEXT NOT NULL,\n"
    "    outcome TEXT NOT NULL,\n"
    "    writes TEXT NOT NULL DEFAULT '[]',\n"
    "    effects TEXT NOT NULL DEFAULT '[]',\n"
    "    capability_accesses TEXT NOT NULL DEFAULT '[]',\n"
    "    invocation_id TEXT NULL,\n"
    "    kind TEXT NOT NULL DEFAULT 'action',\n"
    "    tenant TEXT NOT NULL DEFAULT 'default',\n"
    "    -- The principal that authenticated the call this entry audits (M10,\n"
    "    -- spec `multi-consumer-mcp` AC8/AC10). NULL for every pre-M10 row and\n"
    "    -- for a redelivered outbox effect (§4.2) -- both mean \"we do not know\n"
    "    -- who authenticated\", never \"nobody did\", so no default is correct here.\n"
    "    principal TEXT NULL\n"
    ");\n"
    "\n"
    "-- Indexes for the point-lookup access patterns every read goes\n"
    "-- through: `read_current`/`read_all` (object_type[, id]) and `links_from`/\n"
    "-- `links_to` (link_type + from_id/to_id). Without these, SQLite\n"
    "-- full-scans `objects`/`links` on EVERY lookup -- invisible at\n"
    "-- fixture scale (tens of rows) but O(n^2) once a real ingest puts\n"
    "-- tens of thousands of objects/links in the store.\n"
    "-- Non-behavioral: pure read speedup.\n"
    "CREATE INDEX IF NOT EXISTS idx_objects_type_id\n"
    "    ON objects (tenant, object_type, id);\n"
    "CREATE INDEX IF NOT EXISTS idx_links_from\n"
    "    ON links (tenant, link_type, from_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_links_to\n"
    "    ON links (tenant, link_type, to_id);\n"
    "\n"
    "-- `read_page`/`read_all` filter by `object_type` AND order by\n"
    "-- `row_id` on every page. `row_id` IS the table's physical\n"
    "-- SQLite ROWID (the `INTEGER PRIMARY KEY` alias), but that alone\n"
    "-- does NOT make `object_type = ? ... ORDER BY row_id` free:\n"
    "-- without a compound index covering both columns, SQLite must\n"
    "-- still pick a plan (typically `idx_objects_type_id` above, or a\n"
    "-- full scan) to satisfy the `object_type` filter and then sort\n"
    "-- the matches with a temp b-tree to satisfy `ORDER BY row_id` --\n"
    "-- a per-page sort that makes a full keyset walk O(n^2/batch),\n"
    "-- not O(n) (measured 2612ms vs 116ms at 80k rows with this index\n"
    "-- present). This index lets SQLite satisfy the filter AND the\n"
    "-- order in one pass with zero sort step.\n"
    "CREATE INDEX IF NOT EXISTS idx_objects_type_rowid\n"
    "    ON objects (tenant, object_type, row_id);\n"
    "\n"
    "-- `read_page`'s `after_key` -> `row_id` resolution (see\n"
    "-- the `INVALID_CURSOR` validation rule) is a single indexed point lookup\n"
    "-- on `page_token`, never a scan -- UNIQUE also gives SQLite's\n"
    "-- own constraint enforcement for free (a `page_token` collision\n"
    "-- -- practically impossible for uuid4 -- raises on INSERT\n"
    "-- rather than silently letting two rows share a cursor).\n"
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_objects_page_token\n"
    "    ON objects (page_token);\n"
    "\n"
    "-- The durable effect outbox (spec `durable-effect-outbox` AC1/AC2).\n"
    "-- Deliberately NOT more `audit_log` columns: delivery state\n"
    "-- CHANGES (attempts, next_attempt_at, lease_until), and the audit\n"
    "-- log is append-only. Rows are written inside the emitting\n"
    "-- action's own transaction, so they commit with the ontology\n"
    "-- writes or not at all, and are mutated only by this store's\n"
    "-- claim/release/resolve methods.\n"
    "CREATE TABLE IF NOT EXISTS effect_outbox (\n"
    "    effect_id TEXT PRIMARY KEY,\n"
    "    invocation_id TEXT NOT NULL,\n"
    "    seq INTEGER NOT NULL,\n"
    "    api_name TEXT NOT NULL,\n"
    "    payload TEXT NOT NULL,\n"
    "    action TEXT NOT NULL,\n"
    "    actor_id TEXT NOT NULL,\n"
    "    role TEXT NOT NULL,\n"
    "    emitted_at TEXT NOT NULL,\n"
    "    state TEXT NOT NULL,\n"
    "    attempts INTEGER NOT NULL DEFAULT 0,\n"
    "    next_attempt_at TEXT NOT NULL,\n"
    "    lease_until TEXT NULL,\n"
    "    last_error TEXT NULL,\n"
    "    updated_at TEXT NOT NULL,\n"
    "    tenant TEXT NOT NULL DEFAULT 'default'\n"
    ");\n"
    "\n"
    "-- Emission order is unique per invocation: two rows sharing an\n"
    "-- (invocation_id, seq) would mean one emission was recorded\n"
    "-- twice, so SQLite refuses the second rather than leaving a\n"
    "-- duplicate delivery for the recipient to discover.\n"
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_effect_outbox_invocation_seq\n"
    "    ON effect_outbox (invocation_id, seq);\n"
    "\n"
    "-- `claim_due_effects` filters `state = 'pending' AND\n"
    "-- next_attempt_at <= ?` on every drain. Without this index that is\n"
    "-- a full scan of a table whose delivered/failed rows are kept\n"
    "-- forever (a dead letter a caller can still read is worth more\n"
    "-- than a small table).\n"
    "CREATE INDEX IF NOT EXISTS idx_effect_outbox_due\n"
    "    ON effect_outbox (tenant, state, next_attempt_at);\n"
    "\n"
    "-- Which ontology definition this store's rows were written under\n"
    "-- (spec `ontology-evolution` AC2). One row, ever: `id = 1`.\n"
    "-- Before this table, nothing recorded the SHAPE a row was written\n"
    "-- under, so no reader could tell \"this row predates the change\"\n"
    "-- from \"this row is wrong\" -- which is the only distinction that\n"
    "-- makes a migration possible.\n"
    "CREATE TABLE IF NOT EXISTS ontology_fingerprint (\n"
    "    id INTEGER PRIMARY KEY CHECK (id = 1),\n"
    "    digest TEXT NOT NULL,\n"
    "    types TEXT NOT NULL,\n"
    "    first_seen TEXT NOT NULL,\n"
    "    adopted INTEGER NOT NULL DEFAULT 0,\n"
    "    versions TEXT NOT NULL DEFAULT '{}'\n"
    ");\n"
)


def test_generated_sqlite_ddl_is_pinned() -> None:
    assert schema._SCHEMA_SQL == _EXPECTED_SQLITE_DDL
